using System.Collections;
using System.IO;
using UnityEngine;
using UnityEngine.Networking;

namespace DublinRetrofit
{
    // Reads buildings.json from StreamingAssets and hands the parsed Dataset to ScenarioState.
    // StreamingAssets is copied into builds unchanged, so the data can be regenerated by the
    // Python script without touching any Unity asset.
    public class DatasetLoader : MonoBehaviour
    {
        [SerializeField] string fileName = "buildings.json";

        // Start as a coroutine: on WebGL the file lives on a web server and must be
        // downloaded asynchronously; on desktop it is a normal file we can read directly.
        IEnumerator Start()
        {
            string path = Path.Combine(Application.streamingAssetsPath, fileName);
            string json;

#if UNITY_WEBGL && !UNITY_EDITOR
            using (var request = UnityWebRequest.Get(path))
            {
                yield return request.SendWebRequest();
                if (request.result != UnityWebRequest.Result.Success)
                {
                    Debug.LogError($"Could not download {path}: {request.error}");
                    yield break;
                }
                json = request.downloadHandler.text;
            }
#else
            if (!File.Exists(path))
            {
                Debug.LogError($"Dataset not found at {path}. Run data/build_dataset.py first.");
                yield break;
            }
            json = File.ReadAllText(path);
#endif

            Dataset dataset = JsonUtility.FromJson<Dataset>(json);
            if (dataset?.buildings == null)
            {
                Debug.LogError($"{fileName} did not contain a 'buildings' array.");
                yield break;
            }

            Debug.Log($"Loaded {dataset.buildings.Length} buildings for {dataset.meta.area}");
            ScenarioState.Instance.SetDataset(dataset);
        }
    }
}
